In [1]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import joblib
import converter

df = pd.read_csv('car_sales_cleaned1.csv')
df = df.drop_duplicates()
model = DecisionTreeClassifier()
y = df[['Model']]
mapper = converter.columnsMapper(['Gender', 'Model', 'Color'], df)
dfConverted = converter.convertX(df, mapper)
X = dfConverted[['Gender', 'Color']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
model.fit(X, y)
predictions = model.predict(X_test)
score = accuracy_score(y_test, predictions)
score

0.022838899803536344

In [2]:
joblib.dump(model, 'gender-model-color.joblib')

['gender-model-color.joblib']

In [3]:
dfCompany = pd.read_csv("car_sales_cleaned1.csv", index_col="Company")
dfHyundai = dfCompany.loc["Hyundai"]
dfHyundai

         Gender  Annual Income    Model Transmission       Color  Price ($)
Company
Hyundai  Female         535000   Accent       Manual       Black      18000
Hyundai  Female        1690000   Sonata       Manual       Black      15000
Hyundai    Male         955000  Elantra       Manual  Pale White      26000
Hyundai    Male         457000   Sonata       Manual  Pale White      21000
Hyundai    Male          13500   Sonata       Manual       Black      20000
...         ...            ...      ...          ...         ...        ...
Hyundai  Female          13500  Elantra       Manual         Red      22000
Hyundai  Female          13500   Sonata       Manual       Black      15000
Hyundai  Female         460000   Sonata       Manual       Black      15000
Hyundai    Male         705000   Sonata       Manual         Red      21000
Hyundai    Male         681500   Accent       Manual       Black      18500

[264 rows x 6 columns]

In [4]:
dfToyota = dfCompany.loc["Toyota"].query("`Price ($)` > 40000")
dfToyota

         Gender  Annual Income    Model Transmission       Color  Price ($)
Company
Toyota     Male        1350000   Tacoma         Auto  Pale White      53000
Toyota     Male        1151000  Corolla         Auto  Pale White      41100
Toyota   Female         825000   Tacoma       Manual  Pale White      82000
Toyota   Female          13500  Corolla         Auto  Pale White      41000
Toyota     Male        1326000     RAV4       Manual       Black      85600
...         ...            ...      ...          ...         ...        ...
Toyota     Male        1300000   Celica         Auto  Pale White      45001
Toyota   Female         615000   Tacoma         Auto  Pale White      53000
Toyota     Male        2400000     RAV4       Manual       Black      85000
Toyota     Male         520000   Celica         Auto  Pale White      45000
Toyota     Male        1635000   Tacoma         Auto  Pale White      53501

[199 rows x 6 columns]

In [5]:
column_counts = dfCompany["Model"].value_counts().head(3)
column_counts

Model
Diamante      418
Prizm         411
Silhouette    411
Name: count, dtype: int64